services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8096:8096
      # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_DEVICES=all
      - JELLYFIN_PublishedServerUrl=192.168.0.194
    volumes:
      # - ./config:/config:rw
      - ./alt_config:/config:rw
      - /kyogre/downloads:/downloads
      - /kyogre/movies:/movies
      - /kyogre/shows:/shows

    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
              - nvidia.com/gpu=all


volumes:
  jellyfin-config:
  jellyfin-cache:
