services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    network_mode: host # Enable DLNA and Wake-on-Lan
    volumes:
      - ./config:/config:rw
      - /kyogre/downloads:/downloads
      - /kyogre/movies:/movies
      - /kyogre/show:/shows
    restart: on-failure

volumes:
  jellyfin-config:
  jellyfin-cache:

