services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
      - LOG_CONFS=true
    volumes:
      - ./wg_confs/:/config/wg_confs/
      # /home/corvi/repos/wg_confs/:/config/wg_confs/
      - /lib/modules:/lib/modules/
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      - 9586:9586
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent@sha256:618a145b5792f200da3c3eb556e7234e74c8f83c8486425419645452efd26f25
    container_name: qbittorrent
    network_mode: service:wireguard
    volumes:
      - ./qb-config/qBittorrent.config:/config/qBittorrent/qBittorrent.conf
      - /kyogre/downloads:/downloads:rw
    environment:
      - PUID=0
      - PGID=0
      - LOGS_TO_SDTOUT=true
      - TZ=Europe/London
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    restart: unless-stopped
